#!/bin/bash

log="../log.csv"

echo -n "C,Threaded,$1," >> $log;
make threaded
stat --printf="%s\n" bin/Prac2_threaded >> $log;

for i in {1..100};
	do
	echo "Iteration: $i";
	make run_threaded;
	done
